server:
  port: 8889
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    eureka-server-d-n-s-name: http://${eureka.instance.hostname}:${server.port}/eureka/